### ISSUE TITLE
Sizning css faylingizdagi body elementiga  margin (0) berish kerak

### ISSUE THREAD

**Issue by ErmamatovIslombek** [AsrorTolanov/day-1#1]
1. Sizning css faylingizsagi body elementiga margin: 0; qoshib qoydim.
2. Container ham yozish kerak.
3. * bu elementga ham box-sizing: borde-box; qoshish kerak

**Comment by AsrorTolanov** [comment]
hop rahmat

**Comment by AsrorTolanov** [comment]
tuzatildi
